### ISSUE TITLE
new assert.AssertionError({

### ISSUE THREAD

**Issue by alexlevy0** [Srirangan/googleplaces.js#19]
Hello,

I have a probleme with this sweet googleplaces lib. I try to change location and types but but to do anything it does not work. Cant you help me ?

Thankyou,

Alex

///////////LOG///////////

`./test.sh                                                                             /cygdrive/c/Dev/TimeTroop/MyTimetroopBackApi/node_modules/googleplaces

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Place search must not return 0 results
    at C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\GooglePlacesTest.js:21:16
    at IncomingMessage.<anonymous> (C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\lib\HttpResponseProcessor.js:21:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Place autocomplete request response status is OK
    at C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\PlaceAutocompleteTest.js:16:20
    at IncomingMessage.<anonymous> (C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\lib\HttpResponseProcessor.js:21:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\PlaceDetailsRequestTest.js:20
        placeDetailsRequest({reference: response.results[0].reference}, function (error, response) {
                                                           ^

TypeError: Cannot read property 'reference' of undefined
    at C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\PlaceDetailsRequestTest.js:20:60
    at IncomingMessage.<anonymous> (C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\lib\HttpResponseProcessor.js:21:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Place search must not return 0 results
    at C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\PlaceSearchTest.js:17:16
    at IncomingMessage.<anonymous> (C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\lib\HttpResponseProcessor.js:21:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Text search must not return 0 results
    at C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\TextSearchTest.js:17:16
    at IncomingMessage.<anonymous> (C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\lib\HttpResponseProcessor.js:21:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\PlaceDetailsRequestTest.js:20
        placeDetailsRequest({reference: response.results[0].reference}, function (error, response) {
                                                           ^

TypeError: Cannot read property 'reference' of undefined
    at C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\test\PlaceDetailsRequestTest.js:20:60
    at IncomingMessage.<anonymous> (C:\Dev\TimeTroop\MyTimetroopBackApi\node_modules\googleplaces\lib\HttpResponseProcessor.js:21:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)`

**Comment by alexlevy0** [comment]
Required parameters was missing : radius
